#spring.data.mongodb.uri=mongodb+srv://admin:admin%40123@192.168.1.12/admin
#spring.datasource.url=jdbc:mongodb://192.168.1.12/admin
#spring.datasource.username=admin
spring.data.mongodb.uri=mongodb://192.168.1.12:27017/hrm
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin@123
server.port=8080
spring.graphql.graphiql.enabled=true